### ISSUE TITLE
How can i install the application easily?

### ISSUE THREAD

**Issue by felix2049lou** [tscholze/flutter-surfaceduo-rssbook#3]
Hi, l am a new buyer in surface duo.i search a long time and desire to find a nice rss reader app for surface duo. So, i your app would be the only choose to be the nice RSS reader app in the whole internet. How can I install the app easily?

**Comment by tscholze** [comment]
Hi @felix2049lou nice to meet you.
The app is just a "playground" and an educational app. that means there is no store for it and the rss links are hardcoded.

Nevertheless, thank you! Maybe I'll update the app in the future to make it production-ready!
